data_container:
  image: bluemix-ruby:dev
  volumes:
    - /root
    - /usr/local/bundle
  command: /bin/sh

redis:
  image: redis

elasticsearch:
  image: elasticsearch

kibana:
  image: kibana
  links:
    - elasticsearch:elasticsearch
  ports:
    - 4000:5601

app: &default
  image: bluemix-ruby:dev
  volumes:
    - .:/app
  volumes_from:
    - data_container
  links:
    - redis:redis
    - elasticsearch:elasticsearch
    - kibana:kibana
  ports:
    - 3000:3000
  working_dir: /app
  environment:
    VCAP_SERVICES: |
      {
          "alchemy_api": [ { "credentials": { "apikey": "98cfcb9d595027b5278130e692f69019b9587012" } } ],
          "rediscloud": [ { "credentials": { "hostname": "redis", "port": "6379" } } ]
      }
    ELASTICSEARCH_HOST: elasticsearch
    KIBANA_HOST: kibana

c:
  <<: *default
  command: /bin/bash

s:
  <<: *default
  command: bundle exec unicorn config.ru -p 3000
